### ISSUE TITLE
Käyttäjähallinan suunnittelu

### ISSUE THREAD

**Issue by woltage** [qlma/server#1]
- miten käyttäjät luodaan?
- kuka käyttäjät luo?
- miten oikeudet jaetaan?
- kuka luo ryhmät?

**Comment by kyyberi** [comment]
Tässä kannattaisi tehdä OKM:n kanssa yhteistyötä. Me ollaan EduCloudin puitteisssa tehty jo kansalliseen käyttöön tarkoitettu SSO ja roolienhallintakehikko. Siis tuon kautta tulee tiedot onko opettaja ja missä, missä koulussa lapsi on yms. CSC tekee OKM toimeksisannosta tätä ja pilotit on syksyllä. Vuosi sitten pilotoitiin tunnistus ja nyt sitä on viety lähemmäs tuotantotasoa. Toki vielä pitää meidän ratkoa käyttäjätietojen automaattiseen keräämiseen liittyviä asioita, mutta suunta on että ei kenenkään enää tarvitse tätä tehdä. Me teemme palvelun ja se otetaan käyttöön erilaisissa tuotteissa ja palveluissa. Mukaan on tulossa siis heikot tunnistusmenetelmät, koulujen tunnuksilla kirjautumiset ja KaPA tunnistuksen kanssa yhteentoimivasti, joten sieltä tulee vahva tunnistus. 

Koska pidetään palaveri? Osoite on Meritullinkatu 10 :)

**Comment by woltage** [comment]
@kyyberi Kuulosta hyvältä! 

Voisihan sitä palaveerata. Onko tuosta jotain teknisempää speksiä olemassa?

**Comment by kyyberi** [comment]
Pitää odotella että CSC:n jampat tulee töihin. Meillä jäi repojen siirto kesken ennen kuin rynnättiin lomille. Noista saa ehkä jotain irti
* https://speakerdeck.com/educloudalliance/educloud-auth-sso-status-17-3-2015 
* https://speakerdeck.com/educloudalliance/educloud-auth-sso-status
* https://portal.educloudalliance.org/educloud-tunnistus-valtuutusratkaisu-2015-draft 

Sitten jos on enemmänkin aikaa tuhottavana:
* https://connect.funet.fi/p8zzi1ec14l/ Osuus mitä Henri puhuu
* https://connect.funet.fi/p7pwkuug8uu/ 

Paras tulos tulee jos muutaman kanssa pidetään aika nopeastikin pikku palaveri. Kerrotte mitä olette tekemässä ja minä hommaan CSC:lät jampat kertomaan mitä he puuhaa. Siitä sitten katsotaan miten voisi edetä yhdessä. Sovitaan doodlella aika. Paikkana toimii vaikka paremman puutteessa OKM.

**Comment by woltage** [comment]
CSC ja @kyyberi kanssa sovittu palaveria.
