### ISSUE TITLE
Harmonisoitu kehitysympäristö

### ISSUE THREAD

**Issue by JSomerstone** [qlma/server#2]
Käytän työssäni & harrastusprojekteissani kehitysympäristönä yhdistelmää: VirtualBox + Linux (Centos) Image + Vagrant

Plussia:
- Versionhallittu konfiguraation hallinta
- Kehitysympäristön pystyttäminen helppoa
- Dokumentoi samalla millainen tuotantoympäristön pitää olla
- Ei (juurikaan) "Kyllä se minun koneella toimi" ongelmia

Miinukset:
- Koska virtuaalikone vaatii isäntäkoneelta jonkin verran muistia
- Dependencyt: VirtualBox, Vagrant jotka pitää asentaa enenkuin pääsee koodaamaan

Onko ihmisillä preferenssejä käytettävästä linux-distrosta?

**Comment by jehna** [comment]
Mulla jonkun verran paljon kokemusta PaaS palveluista. Nopeasti listattuna plussat ja miinukset:

Plussat:
- Helppo pystytys
- Yleensä skaalautuvuus (esim. maantieteellinen hajautus, multithreading) valmiiksi mietitty
- Ei vaadi palvelinten päivittelyä; suurin osa sysadmin hommista jää automaattisesti pois, kuten:
  - os:n päivitykset
  - ohjelmistopäivitykset

Miinuksia:
- Sitoo yleensä yhteen palveluntarjoajaan
- Kaikki kirjastot ei välttämättä toimi plug&play

Hyvin kokemuksin suosittelen kyllä kaikkiin projekteihin.

Esimerkkejä:
- (Google App Engine)[https://appengine.google.com]
- (Amazon Elastic Beanstalk)[http://aws.amazon.com/elasticbeanstalk/]

**Comment by jehna** [comment]
Tietty monille suomalaisille julkishallinnon tahoille tuntuu olevan nykypäivänä tärkeää että ohjelmiston saa joko suomalaisille servereille tai kokonaan omille palvelimille pyörimään. Se taitanee tehokkaasti rajata kyllä nuo PaaS palvelut pois käytöstä.

**Comment by woltage** [comment]
Voihan softa olla vaikka PaaSissa, mutta sen saa sitten vietyä vaikka Dockerin avulla helposti muuhun ympäristöön.

Softahan tulee toimimaan helposti: java -jar softa.jar ja tadaa softa on ajossa. Tämän deployaaminen on helppoa vaikka Ansiblen kanssa.

**Comment by t-my** [comment]
+1 Vagrantille ja Dockerille. Vagrantin yhtenä provisiointityökaluna on Docker, eli eivät ole toisiaan poissulkevia. Docker voisi hoitaa deployt ja Vagrant keharin pystytyksen.

**Comment by kyyberi** [comment]
+1 vagrant, docker lähtökohdalle
