### ISSUE TITLE
Määrittely

### ISSUE THREAD

**Issue by jehna** [qlma/server#5]
Ennen kuin kehitysympäristöä #2 (tai mitään muutakaan) lyödään lukkoon, on fiksuinta määritellä mitä tämän open source Wilman halutaan tekevän.

Projektin määrittelyn pitäisi ohjata teknisiä valintoja, eikä suinkaan toisin päin.

Liittyy suurilta osin myös issueen #1.

**Comment by woltage** [comment]
Teimpä nyt tajunnan virtaa #6 tiketille. Saa kommentoida.

**Comment by ilmoraunio** [comment]
Kannattaisiko ensin järjestää organisoitu kysely esim. Facebookin opettajien ICT-ryhmälle ja myös Wilman peruskäyttäjille (niin opettajille kuin oppilaille/opiskelijoille) esimerkiksi lähestymällä jotain/joitain kouluja? On tärkeää selvittää kipukohdat, joita pyrimme ratkaisemaan ennen kuin voimme kunnolla lähteä teknisesti liikkeelle. Ihan ensin olisi myös hyvä tietää, mitä Wilma itsessään tarjoaa. Siitä on jonkun verran aikaa, kun olen itse sitä käyttänyt, ja ymmärtääkseni uusia ominaisuuksia Wilmaan on tullut sitten vuoden 2007. 

Siispä alustavia kysymyksiä: 
- Mitä Wilma tekee oikein?
- Mitä puuttuu?
- Mikä on vaikeaa?
- Mitkä ominaisuudet ovat kuntien kannalta olennaisia? Onko jokin ominaisuus täysin käyttämättä?

**Comment by woltage** [comment]
@ilmoraunio Ensi viikolla käydään läpi että mitä edes lähdetään tavoittelemaan. Haetaanko järjestelmää joka toimi rinnan Wilman kanssa vai jotain muuta. 

Ilman muuta otetaan kouluja ja innostuneita mukaan. Pitäisi tällä viikolla käydä tapaamassa yhden oppilaitoksen edustajia niin voisin heiltä udella myös kiinnostusta.

Mutta kiitos kommentista! Paljon on vielä tehtävää ennen kun päästää liikkeelle.

**Comment by woltage** [comment]
Ensimmäinen MVP tulee olemaan viestit ja niiden välittäminen.

**Comment by jehna** [comment]
@woltage miten tuo viestien välittäminen eroaa kaikista muista maailman ohjelmistoista joilla voi välittää viestejä?

**Comment by woltage** [comment]
@jehna Ei mitenkään.

**Comment by jehna** [comment]
Ehkä minulta on mennyt joku pointti tästä projektista ohi, mutta tartun nyt tuohon trendisanaan, koska hämmästelen, miksi tässä tehdään järjestelmää vain sen vuoksi että tehdään yet another järjestelmä.

Joel Gascoigne totesi [Bufferin mahtavassa blogipostauksessa](https://blog.bufferapp.com/idea-to-paying-customers-in-7-weeks-how-we-did-it) seuraavaa oman tuotteensa MVP:sta:
> I believed that single feature was worthy of its own application. The aim was to create something genuinely useful with a delightful experience.

Samalla tavalla näin tämänkin projektin, kun ensimmäistä kertaa löysin [tweetin](https://twitter.com/iiuusit/status/623206827896012800) aiheesta: Innovointia, paremmin tekemistä ja selvä markkinarako - siis täydellinen tilaisuus muuttaa maailmaa paremmaksi. Tehdä monien ihmisten elämästä parempaa.

Olen tehnyt lukuisia MVP-projekteja, joista useat ovat failanneet, mutta joistakin tullut jopa hittejä. MVP on kuitenkin aina mahdollisuus tehdä jotain eri tavalla kuin kaikki muut; tehdä jokin pieni osa kokonaisuudesta täydellisemmin, tehokkaammin ja paremmin kuin kukaan muu ennen.

Kuitenkin jos ideasta puuttuu punainen lanka - idea, ideologia, uskonto, elämänkatsomus - onko idea silloin elämisen arvoinen? Vetääkö se puoleensa samoin ajattelevia ihmisiä, joista yhteisö muodostuu?

Ei

Joten, vaikka saatan olla liian ulkopuolinen katsoja tälle projektille ja tässä nyt on oikeasti olemassakin joku syy miksi tätä tehdään (muutakin kuin henkilökohtainen koodaamisen harjoittelu), niin uskallan väittää että tuollainen MVP ei tule olemaan "viable product".

**Comment by woltage** [comment]
Mitäs jos tulet tuonne Slackin puolelle? Turhaa me täällä väännetään termeistä tai punaisesta langasta, kun tämä on viestivälineenä aika rajallinen.

**Comment by woltage** [comment]
Tämä ei ole yet another järjestelmä. Tarkoituksena on parantaa käytettävyyttä ja

**Comment by jehna** [comment]
Toki

**Comment by woltage** [comment]
Tarkoituksena ei ole rakentaa yet another järjestelmää, joka tekee täyisin samalla tavalla kaiken. 

Tarkoituksena on hyödyntää viestit järkevästi niin että niihin voidaan tuoda paljon muutakin sisältöä. Tarrat, widgetit, eri formaatit, notifikaatit ja tehdä se niin hyvin kuin mahdollista. Käytettävyys on myös tärkeä.  Niinkun nostit esiin, en todellakaan halua tehdä vain uutta viestintä järjestelmää vaikka yllä sellaisein kuvan sait.

Ja muille: Slackistä voi lukea loput tarinasta.
